
FROM python:3.7

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN mkdir /code
COPY . /code
WORKDIR /code/boardgamebro

EXPOSE 8000

ENV SECRET_KEY=abc
ENV ALLOWED_HOSTS=['*']
ENV INTERNAL_IPS=['127.0.0.1']
# REDDIT
ENV SOCIAL_AUTH_REDDIT_KEY=
ENV SOCIAL_AUTH_REDDIT_SECRET=
# GOOGLE
ENV SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=
ENV SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=
# DISCORD
ENV SOCIAL_AUTH_DISCORD_KEY=
ENV SOCIAL_AUTH_DISCORD_SECRET=

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# EXPOSE 3031
# EXPOSE 9191

