version: '3.1'

services:

  web:
    env_file: .env
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "80:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
