version: '3.1'

services:

  web:
    env_file: .env_dev
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "80:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres 
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresdata_dev:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=developer@boardgamebro.party
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=80
    ports: 
      - "81:80"
    depends_on: 
      - db


volumes:
  postgresdata_dev:
