# Generated by Django 2.1.7 on 2019-03-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgb_app', '0002_auto_20190309_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
