# Generated by Django 2.1.7 on 2019-03-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgb_app', '0003_auto_20190309_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='slug',
            new_name='name',
        ),
        migrations.AddField(
            model_name='play',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
