# Generated by Django 2.1.7 on 2019-03-11 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgb_app', '0004_auto_20190309_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('score', models.IntegerField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgb_app.Play')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(to='bgb_app.Game'),
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bgb_app.Player'),
        ),
    ]
