# Generated by Django 2.1.7 on 2019-03-17 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bgb_app', '0006_auto_20190314_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profile/picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(blank=True, to='bgb_app.Game'),
        ),
        migrations.AddField(
            model_name='player',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgb_app.Profile'),
        ),
    ]
