# Generated by Django 2.1.7 on 2019-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgb_app', '0011_auto_20190318_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='player was deleted at'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email_communication',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Would you like to get awesome news from us?'),
        ),
    ]
