# Generated by Django 2.1.7 on 2019-03-09 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When was the game played?'),
        ),
        migrations.AddField(
            model_name='play',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='core.Player'),
        ),
        migrations.AlterField(
            model_name='play',
            name='game',
            field=models.ForeignKey(help_text='What game was played?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Game'),
        ),
        migrations.AlterField(
            model_name='play',
            name='players',
            field=models.ManyToManyField(help_text='Who was playing?', to='core.Player'),
        ),
    ]
