# Generated by Django 2.1.7 on 2019-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190318_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_player_friends_+', to='core.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='player was deleted at'),
        ),
    ]
