# Generated by Django 2.2.10 on 2020-05-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190403_0835'),
        ('core', '0013_player_created_at'),
    ]

    operations = [
    ]
