# Generated by Django 2.2.10 on 2020-05-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200506_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(blank=True, to='core.Game', verbose_name='Games owned'),
        ),
    ]
